logging:
    level:
        org:
            springframework:
                data:
                    rest: DEBUG
        org.springframework.security: trace
spring:
    jpa:
        hibernate:
#            comment when not in dev mode
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format-sql: true
